subscription_id: 5c9e4789-4852-4ffe-8551-d682affcbd74
resource_group_name: playground-rg
workspace_name: as-playground-w3-ws
compute_name: /subscriptions/5c9e4789-4852-4ffe-8551-d682affcbd74/resourceGroups/playground-rg/providers/Microsoft.MachineLearningServices/virtualclusters/as-playground-w3-ws
instance_type: a100x4
gpu_count_per_node: 4
